/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#f2f0f0",
        "on-primary-fixed-variant": "#6e3900",
        "primary-fixed-dim": "#ffb77d",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#5b4137",
        "on-error": "#ffffff",
        "surface-container-high": "#eae8e7",
        "outline": "#867366",
        "on-secondary-container": "#795c51",
        "secondary-fixed": "#ffdbce",
        "surface-dim": "#dbd9d9",
        "tertiary": "#006d41",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#002110",
        "primary-fixed": "#ffdcc3",
        "surface-variant": "#e4e2e2",
        "surface-tint": "#904d00",
        "on-secondary-fixed": "#2b160f",
        "surface-container": "#efeded",
        "on-tertiary-fixed-variant": "#005230",
        "on-tertiary-container": "#004c2c",
        "primary-container": "#f2994a",
        "background": "#fbf9f8",
        "secondary": "#75584d",
        "error-container": "#ffdad6",
        "inverse-surface": "#303030",
        "inverse-primary": "#ffb77d",
        "tertiary-fixed": "#95f7bb",
        "surface": "#fbf9f8",
        "surface-container-highest": "#e4e2e2",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#60c089",
        "on-primary-container": "#663500",
        "on-surface": "#1b1c1c",
        "on-primary-fixed": "#2f1500",
        "secondary-fixed-dim": "#e4beb2",
        "secondary-container": "#fed7ca",
        "error": "#ba1a1a",
        "primary": "#904d00",
        "surface-bright": "#fbf9f8",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#d9c2b3",
        "surface-container-low": "#f5f3f3",
        "on-background": "#1b1c1c",
        "on-surface-variant": "#544438",
        "tertiary-fixed-dim": "#7adaa1"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "12px",
        "stack-md": "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "gutter": "24px",
        "base": "8px",
        "margin-desktop": "40px",
        "stack-lg": "48px"
      },
      fontFamily: {
        "body-md": ["Quicksand"],
        "caption": ["Quicksand"],
        "label-md": ["Montserrat"],
        "headline-lg-mobile": ["Quicksand"],
        "body-lg": ["Quicksand"],
        "headline-lg": ["Quicksand"],
        "display-lg": ["Quicksand"],
        "headline-md": ["Quicksand"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "caption": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "600"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
